spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:consumer-pat;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console.enabled: true
    console.path: /h2-console

springdoc:
  swagger-ui:
    path: /docs

server:
  port: 8081